#!/usr/bin/env python

#
# Read a dictionary generated by Make-Dictionary.py
#

import pickle
import sys

def mykey(x):
    # We want to key on the number of people. 
    # key = x[0]
    # location, people = x[1]
    # people = x[1][1]
    return(len(x[1][1]))

def main(argv):

    dict_name = sys.argv[1] + '.dic'
    f = open(dict_name, 'r')
    member_dictionary = pickle.load(f)
    f.close()

    for item in sorted(member_dictionary.items(), key=mykey, reverse=True):
        print('key: %s'%item[0]) 
        location = item[1][0]
        people = item[1][1]
        print('  country = %s'%location[0])
        print('  town    = %s'%location[1])
        print('  zipcode = %s'%location[2])
        try: print('  address = %s'%location[3])
        except: print('(Encoding problem printing address?)')
        print('  coords =  %s'%location[4])
        print('  people  = %s'%people)

main(sys.argv)
